### ISSUE TITLE
Add hero banner and favicon

### ISSUE THREAD

**Issue by yangwao** [kodadot/docs#102]
I think just need drop favicon.ico to `/public` folder and that's it

![image](https://github.com/kodadot/docs/assets/5887929/d6ddd400-d679-4819-ab00-30b0131785f5)

plus add hero banner on frontpage would make it more impressive I guess

**Comment by poppyseedDev** [comment]
@exezbcz we need your help here 🐥

**Comment by exezbcz** [comment]
> @exezbcz we need your help here 🐥

I already completed task: send it to Aurora tg 😌

**Comment by poppyseedDev** [comment]
![developers cover](https://github.com/kodadot/docs/assets/30662672/4c2d44d6-6933-42df-9577-b3ea32646170)

**Comment by yangwao** [comment]
I would put a picture on the top
