### ISSUE TITLE
Logo Error on https://docs.kodadot.xyz

### ISSUE THREAD

**Issue by thea-exe** [kodadot/docs#16]
<img width="1509" alt="Screen Shot 2022-04-20 at 1 08 20 AM" src="https://user-images.githubusercontent.com/65369742/164154613-b6ab2a09-c981-4f04-b9a8-2131d50225c9.png">

Top left corner, there's an error on mobile as well but when I ran the docs on my localhost, it had no error

**Comment by cryptodamsky** [comment]
I think i know what is this, will have a look at it tmrw

**Comment by thea-exe** [comment]
@cryptodamsky Still error D:
