### ISSUE TITLE
Comprehensive Hiring page for new talent 

### ISSUE THREAD

**Issue by yangwao** [kodadot/docs#31]
As we are trying build ecosystem of vivid builders experience we would need one page where we can sent everyone with all instructions. 

Whenever me or someone else will be in chat with someone over internet or at physical event we can direct them to one all around page :)

Page should consist of 
- culture of kodadot 
- why they want to join us
- opened job positions, like at https://kodadot.xyz/jobs/
- hiring for frontend like existing process we have in hiring.md https://github.com/kodadot/nft-gallery/blob/main/HIRING.md

Current opened positions we are constantly looking for 

- Frontend Developers (Vue2 + Vue3)
- Rust developer (parachain Dev & Ops & ink! smart contracts)
- Technical Product Manager
- COO
- UI/UX Designer
- Creative Director
- Developer Advocate
- Technical Writer
- Growth & Ops

**Comment by thea-exe** [comment]
I think this should be in nft-gallery instead of documentation? :D

**Comment by thea-exe** [comment]
I can revamp the HIRING.md page in nft-gallery

**Comment by yangwao** [comment]
> I think this should be in nft-gallery instead of documentation? :D

page is shared more easily than .md file tbh :)
i mean have backup here at notion https://metaprime.notion.site/Hiring-for-KodaDot-8fe26b0e03f14500ac3c2ba8704ef123

**Comment by yangwao** [comment]
> I can revamp the HIRING.md page in nft-gallery

approved! :)
