### ISSUE TITLE
Docs.kodadot -> developers.kodadot.xyz

### ISSUE THREAD

**Issue by yangwao** [kodadot/docs#85]
Wyt @kodadot/internal-dev

I want to deploy new vitepress and scrape all old docs to new domain with vitepress 

I see lot of projects using something else than docs. 

Subdomain for developers
---
https://developers.cloudflare.com/d1/get-started/
https://developers.fractal.is/
https://developers.facebook.com/
https://api.magiceden.dev/
https://guide.rarible.com/
https://docs.opensea.io/
https://docs.looksrare.org/
https://docs.alchemy.com/
https://docs.rarible.org/

**Comment by vikiival** [comment]
Yes 🚆

**Comment by yangwao** [comment]
https://developers.kodadot.xyz/
