### ISSUE TITLE
Enrich developers pages 

### ISSUE THREAD

**Issue by yangwao** [kodadot/docs#87]
Sharing slides from my kodadot ecosystem talk 
cc @poppyseeddev

Who we are
---
![image](https://github.com/kodadot/docs/assets/5887929/b2d1feb7-0d16-412e-963b-118e730d3073)

Mission
---

![image](https://github.com/kodadot/docs/assets/5887929/1839a8c9-fbca-4b18-88cd-c75af3cd2f1c)

unlockable-as-sdk
---

![image](https://github.com/kodadot/docs/assets/5887929/21855a8e-0058-4495-b149-2ada244f8ce0)

general overview of tooling
---
![image](https://github.com/kodadot/docs/assets/5887929/1a4c29f5-6d90-4ca7-95e7-371508c64777)

Uniquery
---
![image](https://github.com/kodadot/docs/assets/5887929/8e29bab5-678b-4534-b07f-5887496468ac)

Workers
---
![image](https://github.com/kodadot/docs/assets/5887929/36b38dc4-2ba1-4097-bedc-d5f584ea6d5a)

Indexers
---
![image](https://github.com/kodadot/docs/assets/5887929/721e9c09-0acf-47f4-a9ec-eab4f0279133)

MiniMark
---
![image](https://github.com/kodadot/docs/assets/5887929/6d2417f2-c494-4321-9d5b-5652bb0024f5)

Fandom Shops
---
![image](https://github.com/kodadot/docs/assets/5887929/c9706507-be8c-4070-940c-0c210223a782)

CLI tooling
---
coming soon

![image](https://github.com/kodadot/docs/assets/5887929/c7560f52-0bbf-450c-9e30-30b88277f594)

**Comment by yangwao** [comment]
Coming soon
---
Notification, webhooks
Mailing, custodial walleting

**Comment by yangwao** [comment]
added something 40ab697..7cf1a58

for SEO reasons I would like to keep prefix in pages KodaDot but if there is other way to score good, let's do it.

**Comment by yangwao** [comment]
added something 40ab697..7cf1a58

for SEO reasons I would like to keep prefix in pages KodaDot but if there is other way to score good, let's do it.

**Comment by yangwao** [comment]
Could be put here in this issue

- #61 
- #84

**Comment by poppyseedDev** [comment]
> added something [40ab697](https://github.com/kodadot/docs/commit/40ab6977002535784dcdffbafd009b7b70fe6eec)..[7cf1a58](https://github.com/kodadot/docs/commit/7cf1a58d89b9ba83fb46b3fdfb0bba1b5bc6f1eb)
> 
> for SEO reasons I would like to keep prefix in pages KodaDot but if there is other way to score good, let's do it.

I reordered some files and for better development overview I removed some redunant namings where is kodadot-___ , however I can rename files and add it back, when a set structure of files is detirmened.

**Comment by poppyseedDev** [comment]
First pull request, check sample: https://github.com/kodadot/docs/pull/90

**Comment by poppyseedDev** [comment]
By unlockables as sdk do you have any resources?

@yangwao
